Wifi positioning
UniStuttgart-INS/INSTINCT pull request #6
Opened 2024-07-21 14:38 UTC by rolandlintz

2024-07-30 10:35 UTC, ToppDev requested changes
I started reviewing some things, but then stopped. You need to clean up the PR, otherwise I have to leave a comment every second line.

Also try testing the GUI elements, e.g. the `UartPacketConverter` node is now completely broken with input pin when switching back to other types.

I think from the review items you get a general idea of what we expect. Please clean up the PR and request another review afterwards.

---

Also output from our internal pipelines

<details>
  <summary>Documentation</summary>

```
/builds/instinct/instinct/src/NodeData/WiFi/WiFiPositioningSolution.hpp(22): error: Compound NAV::WiFiPositioningSolution is not documented.
/builds/instinct/instinct/src/util/Vendor/Espressif/EspressifUtilities.hpp(28): error: The following parameter of NAV::vendor::espressif::decryptWiFiObs(const std::shared_ptr< NAV::WiFiObs > &obs, uart::protocol::Packet &packet, const std::string &nameId) is not documented:
  parameter 'nameId'
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.hpp(86): error: Member _sshHostkeys (variable) of class NAV::ArubaSensor is not documented.
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.hpp(87): error: Member _sshKeyExchange (variable) of class NAV::ArubaSensor is not documented.
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.hpp(85): error: Member _sshPassword (variable) of class NAV::ArubaSensor is not documented.
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.hpp(88): error: Member _sshPublickeyAcceptedTypes (variable) of class NAV::ArubaSensor is not documented.
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.hpp(84): error: Member _sshUser (variable) of class NAV::ArubaSensor is not documented.
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.hpp(160): error: Member distance (variable) of struct NAV::WiFiPositioning::Device is not documented.
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.hpp(161): error: Member distanceStd (variable) of struct NAV::WiFiPositioning::Device is not documented.
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.hpp(158): error: Member position (variable) of struct NAV::WiFiPositioning::Device is not documented.
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.hpp(159): error: Member time (variable) of struct NAV::WiFiPositioning::Device is not documented.
```
</details>

<details>
  <summary>Clang-tidy: UartPacketConverter.cpp</summary>

```
/builds/instinct/instinct/src/NodeData/WiFi/WiFiObs.hpp:22:7: error: constructor does not initialize these fields: distance, distanceStd [cppcoreguidelines-pro-type-member-init,hicpp-member-init,-warnings-as-errors]
class WiFiObs : public NodeData
      ^
36858 warnings generated.
Suppressed 36970 warnings (36856 in non-user code, 114 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
```
</details>

<details>
  <summary>Clang-tidy: WiFiPositioning.cpp</summary>

```
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:37:1: error: constructor does not initialize these fields: _numOfDevices [cppcoreguidelines-pro-type-member-init,hicpp-member-init,-warnings-as-errors]
NAV::WiFiPositioning::WiFiPositioning()
^
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:163:85: error: 'data' should be used for accessing the data pointer instead of taking the address of the 0-th element [readability-container-data-pointer,-warnings-as-errors]
                if (ImGui::InputDouble(fmt::format("##InputX{}", rowIndex).c_str(), &_devicePositions.at(rowIndex)[0], 0.0, 0.0, "%.4fm"))
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                    _devicePositions.at(rowIndex).data()
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:184:88: error: 'data' should be used for accessing the data pointer instead of taking the address of the 0-th element [readability-container-data-pointer,-warnings-as-errors]
                if (ImGui::InputDoubleL(fmt::format("##InputLat{}", rowIndex).c_str(), &_devicePositions.at(rowIndex)[0], -180, 180, 0.0, 0.0, "%.8f°"))
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                       _devicePositions.at(rowIndex).data()
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:216:95: error: floating point literal has suffix 'f', which is not uppercase [hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix,-warnings-as-errors]
    if (ImGui::Button(fmt::format("Add Device##{}", size_t(id)).c_str(), ImVec2(columnWidth * 2.1f, 0)))
                                                                                              ^  ~
                                                                                                 F
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:219:29: error: use emplace_back instead of push_back [hicpp-use-emplace,modernize-use-emplace,-warnings-as-errors]
        _deviceMacAddresses.push_back("00:00:00:00:00:00");
                            ^~~~~~~~~~
                            emplace_back(
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:220:26: error: use emplace_back instead of push_back [hicpp-use-emplace,modernize-use-emplace,-warnings-as-errors]
        _devicePositions.push_back(Eigen::Vector3d::Zero());
                         ^~~~~~~~~~
                         emplace_back(
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:226:98: error: floating point literal has suffix 'f', which is not uppercase [hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix,-warnings-as-errors]
    if (ImGui::Button(fmt::format("Delete Device##{}", size_t(id)).c_str(), ImVec2(columnWidth * 2.1f, 0)))
                                                                                                 ^  ~
                                                                                                    F
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:785:9: error: use auto when initializing with a cast to avoid duplicating the type name [hicpp-use-auto,modernize-use-auto,-warnings-as-errors]
        size_t index = static_cast<size_t>(std::distance(_deviceMacAddresses.begin(), it));
        ^~~~~~
        auto
/builds/instinct/instinct/src/Nodes/DataProcessor/WiFi/WiFiPositioning.cpp:882:5: error: do not use 'else' after 'return' [llvm-else-after-return,readability-else-after-return,-warnings-as-errors]
    else
    ^~~~
114711 warnings generated.
Suppressed 115007 warnings (114695 in non-user code, 312 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
9 warnings treated as errors
```
</details>

<details>
  <summary>Clang-tidy: ArubaSensor.cpp</summary>

```
/builds/instinct/instinct/src/NodeData/WiFi/WiFiObs.hpp:22:7: error: constructor does not initialize these fields: distance, distanceStd [cppcoreguidelines-pro-type-member-init,hicpp-member-init,-warnings-as-errors]
class WiFiObs : public NodeData
      ^
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.cpp:26:1: error: constructor does not initialize these fields: _channel, _session [cppcoreguidelines-pro-type-member-init,hicpp-member-init,-warnings-as-errors]
NAV::ArubaSensor::ArubaSensor()
^
/builds/instinct/instinct/src/Nodes/DataProvider/WiFi/Sensors/ArubaSensor.cpp:35:5: error: '_sshHost' should be ini [...]

2024-09-20 11:49 UTC, TheRisenFenix commented on src/NodeData/WiFi/WiFiObs.hpp
> +    NAV::vendor::vectornav::TimeOutputs timeOutputs;
All references that need updating
![image](https://github.com/user-attachments/assets/3abc3459-9653-4146-9d0b-bb918716d192)

2024-09-20 12:59 UTC, TheRisenFenix commented on src/NodeData/WiFi/WiFiObs.hpp
> +    NAV::vendor::vectornav::TimeOutputs timeOutputs;
I don't know if we only need these two struct members, if so I could create a new custom struct with both parameters

2024-09-22 19:02 UTC, ToppDev commented on src/NodeData/WiFi/WiFiObs.hpp
> +    NAV::vendor::vectornav::TimeOutputs timeOutputs;
Yes, creating a custom struct sounds like a good solution

2024-11-27 07:58 UTC, ToppDev commented
This code was internally merged and will be released soon. Closing therefore

2024-11-27 07:58 UTC, closed without merging